url: https://thelukedavis.com
baseurl: 

# Site settings
title: Luke Davis
email: info@lukewdavis.xyz
description: "This site is a personal portfolio. It is meant to reveal all the accomplishment of Luke Davis."


# Team names, titles and social links
people:
- name: Blue Ridge Community College
  pic: 4
  position: Associates Degree - Computer Science
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: linkedin
  #     url: #

- name: James Madison University
  pic: 4
  position: Bachelors Degree - Computer Science Major, Christian Science Minor, Infosed Certificate
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Life
  pic: 4
  position: I have worked a number of jobs that have provided me with opportunities to learn.
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: 
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: 
  - title: bitbucket 
    url: http://bitbucket.org/lwdavis
  - title: github
    url: http://github.com/lukewdavis

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
